export const ranks = [
  {
    id: "lost",
    name: "Заблудшая",
    lore: "Когда звёзды гаснут в её глазах, она идёт вглубь теней, забыв, что искала. Никто не ведёт её, но её шаги слышны сквозь века.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g1.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg1.webp`,
  },
  {
    id: "extinguished",
    name: "Потухшая",
    lore: "Пламя её души угасло, оставив за собой только холодный пепел решимости. В её молчании — ярость, в её взгляде — последняя искра.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g2.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg2.webp`,
  },
  {
    id: "shadoweater",
    name: "Поглот. Тени",
    lore: "Она не живёт — она скользит между мирами, поглощая свет. Там, где была тень — останется только пустота и её след.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g3.web`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg3.webp`,
  },
  {
    id: "singer-of-dusk",
    name: "Певица Угасания",
    lore: "Она играет сумеречную сонату, каждая нота которой заставляет небеса тускнеть, а сердца — замирать навеки.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g4.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg4.webp`,
  },
  {
    id: "bloodseer",
    name: "Кров. Провидица",
    lore: "Её видения вырезаны на плоти, а пророчества — стекают по лезвию. Она читает судьбу в крови, и ни одно предсказание не знает пощады.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g5.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg5.webp`,
  },
  {
    id: "chosen-of-void",
    name: "Избран. Бездны",
    lore: "Она услышала зов, которому не было имени, и ответила. Её шаги несут тишину, способную поглотить даже время.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g6.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg6.webp`,
  },
  {
    id: "deathservant",
    name: "Жанка Смерти",
    lore: "Она не убивает — она завершает. Каждое её прикосновение — как закрытие книги, где последняя страница давно исписана кровью.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g7.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg7.webp`,
  },
  {
    id: "ruthless-lord",
    name: "Безжал. Владыч.",
    lore: "Её трон построен из боли, а венец — из страха. Подданные не преклоняются — они ползут, чтобы не быть раздавленными.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g9.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg9.webp`,
  },
  {
    id: "child-of-chaos",
    name: "Дитя Хаоса",
    lore: "Она смеётся, когда рушатся законы. Пространство изгибается под её взглядами, а реальность трескается от её шагов.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g10.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg10.webp`,
  },
  {
    id: "entity-of-end",
    name: "Сущность Конца",
    lore: "Она — не приход. Она — завершение. В её присутствии исчезают желания, имена и смысл. Остаётся лишь конец.",
    modelImage: `${import.meta.env.BASE_URL}images/images/g11.webp`,
    backgroundImage: `${import.meta.env.BASE_URL}images/images/bg11.webp`,
  },
];
