export const ranks = [
  {
    id: "lost",
    name: "Заблудший",
    lore: "Когда звёзды гаснут в её глазах, она идёт вглубь теней, забыв, что искала. Никто не ведёт её, но её шаги слышны сквозь века.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g1.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg1.webp`,
  },
  {
    id: "extinguished",
    name: "Потухший",
    lore: "Пламя её души угасло, оставив за собой только холодный пепел решимости. В её молчании — ярость, в её взгляде — последняя искра.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g2.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg2.webp`,
  },
  {
    id: "shadoweater",
    name: "Поглот. Тени",
    lore: "Она не живёт — она скользит между мирами, поглощая свет. Там, где была тень — останется только пустота и её след.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g3.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg3.webp`,
  },
  {
    id: "singer-of-dusk",
    name: "Певец Угасания",
    lore: "Она играет сумеречную сонату, каждая нота которой заставляет небеса тускнеть, а сердца — замирать навеки.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g4.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg4.webp`,
  },
  {
    id: "bloodseer",
    name: "Кров. Провидец",
    lore: "Её видения вырезаны на плоти, а пророчества — стекают по лезвию. Она читает судьбу в крови, и ни одно предсказание не знает пощады.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g5.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg5.webp`,
  },
  {
    id: "chosen-of-void",
    name: "Избран. Бездны",
    lore: "Она услышала зов, которому не было имени, и ответила. Её шаги несут тишину, способную поглотить даже время.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g6.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg6.webp`,
  },
  {
    id: "deathservant",
    name: "Слуга Смерти",
    lore: "Она не убивает — она завершает. Каждое её прикосновение — как закрытие книги, где последняя страница давно исписана кровью.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g7.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg7.webp`,
  },
  {
    id: "ruthless-lord",
    name: "Безжал. Владыка",
    lore: "Её трон построен из боли, а венец — из страха. Подданные не преклоняются — они ползут, чтобы не быть раздавленными.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g9.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg9.webp`,
  },
  {
    id: "child-of-chaos",
    name: "Дитя Хаоса",
    lore: "Она смеётся, когда рушатся законы. Пространство изгибается под её взглядами, а реальность трескается от её шагов.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g10.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg10.webp`,
  },
  {
    id: "entity-of-end",
    name: "Сущность Конца",
    lore: "Она — не приход. Она — завершение. В её присутствии исчезают желания, имена и смысл. Остаётся лишь конец.",
    modelImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/g11.webp`,
    backgroundImage: `https://raw.githubusercontent.com/Taskov1ch/Aurion/main/site_assets/bg11.webp`,
  },
];
