export const ranks = [
  {
    id: "lost",
    name: "Заблудшая",
    lore: "Когда звёзды гаснут в её глазах, она идёт вглубь теней, забыв, что искала. Никто не ведёт её, но её шаги слышны сквозь века.",
    modelImage: "/images/g1.webp",
    backgroundImage: "/images/bg1.webp",
  },
  {
    id: "extinguished",
    name: "Потухшая",
    lore: "Пламя её души угасло, оставив за собой только холодный пепел решимости. В её молчании — ярость, в её взгляде — последняя искра.",
    modelImage: "/images/g2.webp",
    backgroundImage: "/images/bg2.webp",
  },
  {
    id: "shadoweater",
    name: "Поглот. Тени",
    lore: "Она не живёт — она скользит между мирами, поглощая свет. Там, где была тень — останется только пустота и её след.",
    modelImage: "/images/g3.webp",
    backgroundImage: "/images/bg3.webp",
  },
  {
    id: "singer-of-dusk",
    name: "Певица Угасания",
    lore: "Она играет сумеречную сонату, каждая нота которой заставляет небеса тускнеть, а сердца — замирать навеки.",
    modelImage: "/images/g4.webp",
    backgroundImage: "/images/bg4.webp",
  },
  {
    id: "bloodseer",
    name: "Кров. Провидица",
    lore: "Её видения вырезаны на плоти, а пророчества — стекают по лезвию. Она читает судьбу в крови, и ни одно предсказание не знает пощады.",
    modelImage: "/images/g5.webp",
    backgroundImage: "/images/bg5.webp",
  },
  {
    id: "chosen-of-void",
    name: "Избран. Бездны",
    lore: "Она услышала зов, которому не было имени, и ответила. Её шаги несут тишину, способную поглотить даже время.",
    modelImage: "/images/g6.webp",
    backgroundImage: "/images/bg6.webp",
  },
  {
    id: "deathservant",
    name: "Жанка Смерти",
    lore: "Она не убивает — она завершает. Каждое её прикосновение — как закрытие книги, где последняя страница давно исписана кровью.",
    modelImage: "/images/g7.webp",
    backgroundImage: "/images/bg7.webp",
  },
  {
    id: "ruthless-lord",
    name: "Безжал. Владыч.",
    lore: "Её трон построен из боли, а венец — из страха. Подданные не преклоняются — они ползут, чтобы не быть раздавленными.",
    modelImage: "/images/g9.webp",
    backgroundImage: "/images/bg9.webp",
  },
  {
    id: "child-of-chaos",
    name: "Дитя Хаоса",
    lore: "Она смеётся, когда рушатся законы. Пространство изгибается под её взглядами, а реальность трескается от её шагов.",
    modelImage: "/images/g10.webp",
    backgroundImage: "/images/bg10.webp",
  },
  {
    id: "entity-of-end",
    name: "Сущность Конца",
    lore: "Она — не приход. Она — завершение. В её присутствии исчезают желания, имена и смысл. Остаётся лишь конец.",
    modelImage: "/images/g11.webp",
    backgroundImage: "/images/bg11.webp",
  },
];
